import type { WeddingConfig } from './types'

/**
 * Edit this file to update wedding content.
 * Visual design lives in style.css — keep content and look separate.
 */
export const wedding: WeddingConfig = {
  couple: {
    partnerOne: 'Thamanna',
    partnerTwo: 'Samar',
    monogram: 'T&S',
    instagram: {
      thamanna: 'typicalthamannathings',
      samar: 'itsa.me.samario',
    },
  },
  receptionDate: '2026-10-04T18:00:00+05:30',
  tagline: '31 MAY 2025',
  quote: 'The adventure continues — we are already married.',
  heroImage: '/images/hero.jpg',
  story: {
    title: 'How It Started',
    image: '/images/gallery/2025-09-25(3).jpg',
    imageAlt: 'Thamanna and Samar',
    paragraphs: [
      'On September 11th, our paths crossed in the picturesque hills of Macclesfield. The moment we met, an inexplicable sense of calm washed over—like finding a quiet, peaceful sanctuary in the middle of the world.',
      'It didn’t take long to realize we were natural trail mates. Our very first adventure together took us up Tegg’s Nose, where we tackled the trails, took in the sweeping countryside views, and shared our very first cup of coffee at the Tegg’s Nose Cafe.',
      'Many hikes, coffee cups, and shared adventures later, we are already married. A year on, we’re simply sharing our joy with all of you — we can’t wait to celebrate this next chapter together.',
    ],
  },
  events: [
    {
      id: 'meeting',
      title: 'First Meeting',
      date: 'Wednesday, 11 September 2024',
      time: '',
      venue: 'Macclesfield',
      address: 'United Kingdom',
      description: 'Where our paths first crossed, in the hills of Macclesfield.',
      theme: 'meeting',
      icon: '△',
    },
    {
      id: 'nikah',
      title: 'Nikah',
      date: 'Saturday, 31 May 2025',
      time: '',
      venue: 'Hyatt Regency',
      address: 'Thrissur, Kerala',
      description: 'Our Nikah was solemnized on this day.',
      theme: 'nikah',
      icon: '☾',
    },
    {
      id: 'haldi',
      title: 'Haldi',
      date: 'Thursday, 1 October 2026',
      time: '10:00 AM',
      venue: 'Venue name',
      address: 'Street, City',
      description:
        'A morning of turmeric, laughter, and blessings under the sun. Come ready to be coloured.',
      theme: 'haldi',
      icon: '✿',
      dressCode: 'Yellows, whites and gold',
      dressNote: 'Come ready to be coloured. White trainers are a brave choice.',
    },
    {
      id: 'mehendi',
      title: 'Mehendi',
      date: 'Thursday, 1 October 2026',
      time: '6:00 PM',
      venue: 'Venue name',
      address: 'Street, City',
      description:
        'Henna, dhol, and full volume celebration. Stay right till the very end — the night has something planned.',
      theme: 'mehendi',
      icon: '❦',
      dressCode: 'The brightest thing you own',
      dressNote: 'If it would startle a sheep on Tegg’s Nose, it belongs here.',
    },
    {
      id: 'sangeet',
      title: 'Sangeet',
      date: 'Friday, 2 October 2026',
      time: '7:00 PM',
      venue: 'Venue name',
      address: 'Street, City',
      description:
        'Performances, dancing, and a night that belongs on screen. Bring your best moves.',
      theme: 'sangeet',
      icon: '♪',
      dressCode: 'Dress to impress',
      dressNote:
        'No hiking boots required for this one — though comfortable dancing shoes are encouraged!',
    },
    {
      id: 'reception',
      title: 'Reception',
      date: 'Sunday, 4 October 2026',
      time: '6:00 PM',
      venue: 'Green Oak Convention Center',
      address: 'Thurayur, Calicut, Kerala 673523',
      description:
        'An evening of dinner, music, and slow celebration with everyone we love.',
      theme: 'reception',
      icon: '✦',
      dressCode: 'Dress to impress',
      dressNote:
        'No hiking boots required for this one — though comfortable dancing shoes are encouraged!',
    },
  ],
  gallery: [
    { src: '/images/gallery/2025-09-23.jpg', alt: 'Thamanna and Samar' },
    { src: '/images/gallery/2025-09-23(1).jpg', alt: 'Thamanna and Samar' },
    { src: '/images/gallery/2025-09-23(2).jpg', alt: 'Thamanna and Samar' },
    { src: '/images/gallery/2025-09-23(3).jpg', alt: 'Thamanna and Samar' },
    { src: '/images/gallery/2025-09-23(4).jpg', alt: 'Thamanna and Samar' },
    { src: '/images/gallery/2025-09-23(5).jpg', alt: 'Thamanna and Samar' },
    { src: '/images/gallery/2025-09-23(6).jpg', alt: 'Thamanna and Samar' },
    { src: '/images/gallery/2025-09-23(7).jpg', alt: 'Thamanna and Samar' },
    { src: '/images/gallery/2025-09-23(8).jpg', alt: 'Thamanna and Samar' },
    { src: '/images/gallery/2025-09-23(9).jpg', alt: 'Thamanna and Samar' },
    { src: '/images/gallery/2025-09-23(10).jpg', alt: 'Thamanna and Samar' },
    { src: '/images/gallery/2025-09-23(11).jpg', alt: 'Thamanna and Samar' },
    { src: '/images/gallery/2025-09-23(12).jpg', alt: 'Thamanna and Samar' },
    { src: '/images/gallery/2025-09-23(13).jpg', alt: 'Thamanna and Samar' },
    { src: '/images/gallery/2025-09-23(14).jpg', alt: 'Thamanna and Samar' },
    { src: '/images/gallery/2025-09-23(15).jpg', alt: 'Thamanna and Samar' },
    { src: '/images/gallery/2025-09-23(16).jpg', alt: 'Thamanna and Samar' },
    { src: '/images/gallery/2025-09-23(17).jpg', alt: 'Thamanna and Samar' },
    { src: '/images/gallery/2025-09-23(18).jpg', alt: 'Thamanna and Samar' },
    { src: '/images/gallery/2025-09-25.jpg', alt: 'Thamanna and Samar' },
    { src: '/images/gallery/2025-09-25(1).jpg', alt: 'Thamanna and Samar' },
    { src: '/images/gallery/2025-09-25(2).jpg', alt: 'Thamanna and Samar' },
    { src: '/images/gallery/2025-09-25(3).jpg', alt: 'Thamanna and Samar' },
    { src: '/images/gallery/2025-09-25(4).jpg', alt: 'Thamanna and Samar' },
    { src: '/images/gallery/2025-09-25(5).jpg', alt: 'Thamanna and Samar' },
    { src: '/images/gallery/2025-09-25(6).jpg', alt: 'Thamanna and Samar' },
    { src: '/images/gallery/2025-09-25(7).jpg', alt: 'Thamanna and Samar' },
    { src: '/images/gallery/2025-09-25(8).jpg', alt: 'Thamanna and Samar' },
    { src: '/images/gallery/2025-09-25(9).jpg', alt: 'Thamanna and Samar' },
    { src: '/images/gallery/2025-09-25(10).jpg', alt: 'Thamanna and Samar' },
    { src: '/images/gallery/2025-09-25(11).jpg', alt: 'Thamanna and Samar' },
    { src: '/images/gallery/2025-09-25(12).jpg', alt: 'Thamanna and Samar' },
    { src: '/images/gallery/2025-09-25(13).jpg', alt: 'Thamanna and Samar' },
    { src: '/images/gallery/2025-09-25(14).jpg', alt: 'Thamanna and Samar' },
    { src: '/images/gallery/2025-09-25(15).jpg', alt: 'Thamanna and Samar' },
    { src: '/images/gallery/2025-09-25(16).jpg', alt: 'Thamanna and Samar' },
    { src: '/images/gallery/2025-09-25(17).jpg', alt: 'Thamanna and Samar' },
    { src: '/images/gallery/2025-09-25(18).jpg', alt: 'Thamanna and Samar' },
    {
      src: '/images/gallery/placeholder-1.svg',
      alt: 'A photograph from our years together',
      category: 'years',
    },
    {
      src: '/images/gallery/placeholder-2.svg',
      alt: 'A photograph from our years together',
      category: 'years',
    },
    {
      src: '/images/gallery/placeholder-3.svg',
      alt: 'A photograph from our years together',
      category: 'years',
    },
    {
      src: '/images/gallery/placeholder-4.svg',
      alt: 'A photograph from our years together',
      category: 'years',
    },
  ],
  feed: {
    stories: [
      {
        id: 'engagement',
        label: 'Engagement',
        status: 'replay',
        image: '/images/gallery/2025-09-23.jpg',
      },
      {
        id: 'nikah',
        label: 'Nikah',
        status: 'replay',
        image: '/images/gallery/2025-09-25.jpg',
      },
      {
        id: 'live',
        label: 'Live',
        status: 'live',
        image: '/images/gallery/2025-09-25(3).jpg',
      },
      { id: 'haldi', label: 'Haldi', status: 'coming', icon: '✿', caption: 'October prep has officially taken over our lives. Lists, spreadsheets, and a mild amount of chaos.' },
      { id: 'mehendi', label: 'Mehendi', status: 'coming', icon: '❦', caption: 'Right hand only until this dries. Left hand if you need a photo.' },
      { id: 'sangeet', label: 'Sangeet', status: 'coming', icon: '♪', caption: 'Backstage. Deep breath. We know at least half the steps.' },
      { id: 'reception', label: 'Reception', status: 'coming', icon: '✦', caption: 'Last dance of the week. Feet are done but the floor is still calling.' },
    ],
    posts: [
      {
        date: '2025-05-31T10:30:00+05:30',
        author: 'Thamanna & Samar',
        handle: '@itsa.me.samario',
        body: 'Nikah morning. Thamanna is getting ready and I am doing a terrible job of acting normal.',
        image: '/images/gallery/2025-09-25(3).jpg',
        imageAlt: 'Thamanna and Samar',
        gallery: ['/images/gallery/2025-09-25(7).jpg', '/images/gallery/2025-09-25(11).jpg'],
        location: 'Hyatt Regency',
        likes: 48,
        likedBy: 'drape.or.die',
        comments: [
          { handle: '@drape.or.die', body: 'THE DRAPE 😭 this is it' },
          { handle: '@already.in.tears', body: 'You look unreal in this light' },
        ],
        live: true,
      },
      {
        date: '2025-05-17T16:00:00+05:30',
        author: 'Thamanna & Samar',
        handle: '@typicalthamannathings',
        body: 'Golden hour did its thing today. Hard to pick just one from this roll.',
        image: '/images/gallery/2025-09-23(4).jpg',
        imageAlt: 'Thamanna and Samar',
        gallery: ['/images/gallery/2025-09-23(9).jpg'],
        location: 'Somewhere between two families',
        likes: 112,
        likedBy: 'uncle.with.the.frame',
        comments: [
          { handle: '@uncle.with.the.frame', body: 'This is the one for the wall. No debate.' },
          { handle: '@out.of.office.till.october', body: 'How are you both this photogenic in one frame' },
        ],
      },
      {
        date: '2025-05-17T11:20:00+05:30',
        author: 'Thamanna & Samar',
        handle: '@typicalthamannathings',
        body: 'Engagement weekend still living rent free in my head. Two proposals, two yeses, zero chill since.',
        image: '/images/gallery/2025-09-23.jpg',
        imageAlt: 'Thamanna and Samar after their engagement',
        location: 'Dorset & Kochi',
        likes: 64,
        likedBy: 'amma.still.crying',
        comments: [{ handle: '@amma.still.crying', body: 'We are still crying. Both yeses were perfect.' }],
      },
      {
        date: '2025-05-31T18:00:00+05:30',
        author: 'Thamanna & Samar',
        handle: '@typicalthamannathings',
        body: 'Married this morning. Quiet, full, and still catching my breath 🤍',
        image: '/images/gallery/2025-09-25.jpg',
        imageAlt: 'Thamanna and Samar on their Nikah day',
        gallery: ['/images/gallery/2025-09-25(14).jpg', '/images/gallery/2025-09-25(5).jpg'],
        location: 'Nikah — 31 May 2025',
        likes: 240,
        likedBy: 'groupchat.on.mute',
        pinned: true,
        comments: [
          { handle: '@groupchat.on.mute', body: 'Our hearts are so full today' },
          { handle: '@itsa.me.samario', body: 'Best yes I have ever said' },
        ],
      },
    ],
  },
  photoUpload: {
    url: '',
    note: 'Took a photo you love? Scan the code and drop it into our shared album — we want to see the night through your eyes.',
  },
  rsvp: {
    /** Optional Formspree URL. Leave empty to keep replies in the browser for now. */
    endpoint: '',
    deadline: '1 September 2026',
    note: 'We would love to know if you will be present for the events.',
  },
  soundtrack: {
    title: 'Soundtracks of Our Life',
    lede: 'Nine songs for the hills, the coast, two yeses, and a quiet morning in May.',
    tracks: [
      {
        id: 'macclesfield',
        title: 'First Crossing',
        moment: 'Macclesfield · 11 Sep 2024',
        src: '/audio/01-first-crossing.mp3',
      },
      {
        id: 'teggs-nose',
        title: 'Tea at the Top',
        moment: "Tegg's Nose · first hike",
        src: '/audio/02-tea-at-the-top.mp3',
      },
      {
        id: 'dorset',
        title: 'He Asked by the Sea',
        moment: 'Dorset coast',
        src: '/audio/03-he-asked.mp3',
      },
      {
        id: 'kochi',
        title: 'She Asked in Kochi',
        moment: 'Pepper House',
        src: '/audio/04-she-asked.mp3',
      },
      {
        id: 'nikah',
        title: 'Already Married',
        moment: 'Nikah · 31 May 2025',
        src: '/audio/05-already-married.mp3',
      },
      {
        id: 'haldi',
        title: 'Yellow Everywhere',
        moment: 'Haldi',
        src: '/audio/06-yellow-everywhere.mp3',
      },
      {
        id: 'mehendi',
        title: 'Right Hand Drying',
        moment: 'Mehendi',
        src: '/audio/07-right-hand.mp3',
      },
      {
        id: 'sangeet',
        title: 'Half the Steps',
        moment: 'Sangeet',
        src: '/audio/08-half-the-steps.mp3',
      },
      {
        id: 'reception',
        title: 'Last Dance of the Week',
        moment: 'Reception',
        src: '/audio/09-last-dance.mp3',
      },
    ],
  },
  trail: {
    title: 'The Trail So Far',
    lede: 'Tap each pin and walk the path with us — from a first hello in Macclesfield to the day we said I do.',
    stops: [
      {
        id: 'macclesfield',
        title: 'Macclesfield',
        kicker: 'Where it began',
        description:
          '11 September, in the hills above town. A chance meeting, a sudden calm — as if the Peak District had been keeping a seat for us.',
        image: '/images/trail/macclesfield.png',
        imageAlt: 'Thamanna and Samar on a hillside near Macclesfield',
        mapUrl: 'https://maps.google.com/?q=Macclesfield',
      },
      {
        id: 'dorset',
        title: 'Dorset',
        kicker: 'He asked',
        description:
          'On the Dorset coast, Samar asked the first question — a quiet moment by the sea, and a yes that started everything properly.',
        image: '/images/trail/dorset.png',
        imageAlt: 'Samar proposing to Thamanna on the Dorset coast',
        mapUrl: 'https://maps.google.com/?q=Dorset',
      },
      {
        id: 'pepper-house',
        title: 'Pepper House, Kochi',
        kicker: 'She asked',
        description:
          'At Pepper House in Kochi, Thamanna returned the question. Two proposals, two yeses — and a story we still love telling.',
        image: '/images/trail/pepper-house.png',
        imageAlt: 'Thamanna proposing to Samar at Pepper House, Kochi',
        mapUrl: 'https://maps.google.com/?q=Pepper+House+Kochi',
      },
      {
        id: 'hyatt',
        title: 'Hyatt Regency, Thrissur',
        kicker: 'The day we said I do',
        description:
          'Our Nikah at Hyatt Regency, Thrissur — 31 May 2025. The day we became husband and wife, surrounded by everyone we love.',
        image: '/images/trail/hyatt.png',
        imageAlt: 'Thamanna and Samar signing at their Nikah',
        mapUrl: 'https://maps.google.com/?q=Hyatt+Regency+Thrissur',
      },
      {
        id: 'home',
        title: 'Where We Live',
        kicker: 'Plot twist',
        description: 'Haha, tricked you! You are a nosy one.',
      },
    ],
  },
  quiz: {
    title: 'A Little Trivia',
    lede: 'Eight cheeky questions. One right answer each — how well do you really know us?',
    questions: [
      {
        id: 'hike',
        prompt: 'Who survived the hike better on Day 1?',
        options: [
          { id: 'thamanna', label: 'Thamanna' },
          { id: 'samar', label: 'Samar' },
          { id: 'tie', label: 'They both needed a sit-down' },
        ],
        answerId: 'samar',
        coupleNote: 'Samar claims the summit. Thamanna claims the moral victory. The tea room claims them both.',
      },
      {
        id: 'tea',
        prompt: 'How many cups of tea do we drink together in a week?',
        options: [
          { id: 'four', label: 'A polite four' },
          { id: 'eight', label: 'About eight' },
          { id: 'twelve', label: 'Twelve, easily' },
          { id: 'lost', label: 'We lost count' },
        ],
        answerId: 'lost',
        coupleNote: 'The official tally is “we lost track around cup nine.” The kettle disagrees.',
      },
      {
        id: 'lost',
        prompt: 'Who is more likely to get lost on a trail?',
        options: [
          { id: 'thamanna', label: 'Thamanna' },
          { id: 'samar', label: 'Samar' },
          { id: 'both', label: 'Both, confidently' },
        ],
        answerId: 'thamanna',
        coupleNote: 'Thamanna took a “shortcut.” Samar had the map. A sheep was still asked for directions.',
      },
      {
        id: 'asked',
        prompt: 'Who asked first?',
        options: [
          { id: 'samar', label: 'Samar, on the Dorset coast' },
          { id: 'thamanna', label: 'Thamanna, at Pepper House' },
          { id: 'both', label: 'Both — it took two yeses' },
        ],
        answerId: 'samar',
        coupleNote: 'Samar asked by the sea first. Thamanna asked later in Kochi — two yeses, one very good story.',
      },
      {
        id: 'coffee',
        prompt: 'Which of our spots is really for midnight tea?',
        options: [
          { id: 'shell', label: 'Shell at KIAL' },
          { id: 'adda', label: 'Baggalur Adda' },
          { id: 'namdroling', label: 'Namdroling Monastery Café' },
        ],
        answerId: 'adda',
        coupleNote:
          'Baggalur Adda stays open late enough for “just one more chai.” The Shell is for early flights; the monastery is for daylight.',
      },
      {
        id: 'snacks',
        prompt: 'Who packs the better trail snacks?',
        options: [
          { id: 'thamanna', label: 'Thamanna' },
          { id: 'samar', label: 'Samar' },
          { id: 'shop', label: 'Whoever finds a shop first' },
        ],
        answerId: 'thamanna',
        coupleNote: 'Thamanna packed the good stuff. Samar packed optimism. The café at the top still looked tempting.',
      },
      {
        id: 'flight',
        prompt: 'Who falls asleep first on a flight?',
        options: [
          { id: 'thamanna', label: 'Thamanna, before take-off' },
          { id: 'samar', label: 'Samar, somewhere over the sea' },
          { id: 'both', label: 'Both, and nobody minds the bags' },
        ],
        answerId: 'thamanna',
        coupleNote: 'One is out before the safety video. The other is “just resting their eyes.” The bags are fine. Probably.',
      },
      {
        id: 'where',
        prompt: 'Where do we actually live?',
        options: [
          { id: 'peak', label: 'The Peak District, obviously' },
          { id: 'kerala', label: 'Kerala, between visits' },
          { id: 'nosy', label: 'Nice try — that\'s classified wedding intel' },
        ],
        answerId: 'nosy',
        coupleNote: 'Haha, tricked you. The trail map already warned you about this one.',
      },
    ],
  },
  guide: {
    title: 'Places We Keep Going Back To',
    lede: 'A hill, a monastery café, an adda, and the airport Shell — if you have a spare morning, these are ours.',
    completeNote:
      'Four for four. You have now officially been on more of our dates than most of our friends — come find us and claim your tea.',
    places: [
      {
        id: 'namdroling',
        title: 'Namdroling Monastery Café',
        kind: 'coffee',
        kicker: 'Bylakuppe',
        note: 'After the Golden Temple in Bylakuppe. Tibetan tea, laphing we never skip, a quiet table, and as much time as the courtyard will give you.',
        tip: 'Butter tea once for the story, sweet tea twice for the taste, laphing every time. Then sit until somebody rings a bell.',
        travel: '5 hours west, worth every one',
        stamp: 'Butter tea, no regrets',
        mapUrl: 'https://maps.google.com/?q=Namling+Cafe+Namdroling+Monastery+Bylakuppe',
      },
      {
        id: 'adda',
        title: 'Baggalur Adda',
        kind: 'coffee',
        kicker: 'North Bengaluru',
        note: 'Our north-Bangalore hangout. Order whatever is on the board and stay longer than you meant to.',
        tip: 'Best french fries and chai. Whatever is chalked on the board that morning — ask for a second round, you will want one.',
        travel: '40 minutes and one wrong turn',
        stamp: 'Stayed far too long',
        mapUrl: 'https://maps.google.com/?q=Bagalur+Adda+Bengaluru',
      },
      {
        id: 'kial',
        title: 'Shell at KIAL',
        kind: 'coffee',
        kicker: 'On the airport road',
        note: 'The airport pit stop — coffee, a stretch of the legs, then you are on your way.',
        tip: 'Best spot for tea in the middle of the night. Coffee, a stretch, and a plane low enough to duck — ten minutes, every single time.',
        travel: 'Ten minutes before every flight',
        stamp: 'Fuelled and airborne',
        mapUrl: 'https://maps.google.com/?q=Shell+Kempegowda+International+Airport+Mylanahalli',
      },
      {
        id: 'basadibetta',
        title: 'Basadibetta',
        kind: 'hike',
        kicker: 'Mandaragiri, Tumakuru',
        note: 'Mandaragiri — four hundred steps, Jain temples at the top, and a view that is worth the climb. Easy, unhurried, generous.',
        tip: 'Best spot to feel calm. Four hundred steps — go before the sun does, carry water, and count out loud if it helps.',
        travel: '90 minutes north, 400 steps up',
        stamp: 'All four hundred steps',
        mapUrl: 'https://maps.google.com/?q=Basadi+Betta+Mandaragiri+Tumakuru',
      },
    ],
  },
}
