import type { WeddingConfig } from './types'

/**
 * Edit this file to update wedding content.
 * Visual design lives in style.css — keep content and look separate.
 */
export const wedding: WeddingConfig = {
  couple: {
    partnerOne: 'Thamanna',
    partnerTwo: 'Samar',
    monogram: 'T&S',
  },
  receptionDate: '2026-10-04T18:00:00+05:30',
  tagline: '31 MAY 2025',
  quote: 'The adventure continues — we are already married.',
  heroImage: '/images/hero.jpg',
  story: {
    title: 'How It Started',
    image: '/images/gallery/2025-09-25(3).jpg',
    imageAlt: 'Thamanna and Samar',
    paragraphs: [
      'On September 11th, our paths crossed in the picturesque hills of Macclesfield. The moment we met, an inexplicable sense of calm washed over—like finding a quiet, peaceful sanctuary in the middle of the world.',
      'It didn’t take long to realize we were natural trail mates. Our very first adventure together took us up Tegg’s Nose, where we tackled the trails, took in the sweeping countryside views, and shared our very first cup of coffee at the Tegg’s Nose Cafe.',
      'Many hikes, coffee cups, and shared adventures later, we are already married. A year on, we’re simply sharing our joy with all of you — we can’t wait to celebrate this next chapter together.',
    ],
  },
  events: [
    {
      id: 'meeting',
      title: 'First Meeting',
      date: 'Wednesday, 11 September 2024',
      time: '',
      venue: 'Macclesfield',
      address: 'United Kingdom',
      description: 'Where our paths first crossed, in the hills of Macclesfield.',
      theme: 'meeting',
      icon: '△',
    },
    {
      id: 'nikah',
      title: 'Nikah',
      date: 'Saturday, 31 May 2025',
      time: '',
      venue: 'Hyatt Regency',
      address: 'Thrissur',
      description: 'Our Nikah was solemnized on this day.',
      theme: 'nikah',
      icon: '☾',
    },
    {
      id: 'haldi',
      title: 'Haldi',
      date: 'Thursday, 1 October 2026',
      time: '10:00 AM',
      venue: 'Venue name',
      address: 'Street, City',
      description:
        'A morning of turmeric, laughter, and blessings under the sun. Come ready to be coloured.',
      theme: 'haldi',
      icon: '✿',
      dressCode: 'Yellows, whites and gold',
      dressNote: 'Come ready to be coloured. White trainers are a brave choice.',
    },
    {
      id: 'mehendi',
      title: 'Mehendi',
      date: 'Thursday, 1 October 2026',
      time: '6:00 PM',
      venue: 'Venue name',
      address: 'Street, City',
      description:
        'Henna, dhol, and full volume celebration. Stay right till the very end — the night has something planned.',
      theme: 'mehendi',
      icon: '❦',
      dressCode: 'The brightest thing you own',
      dressNote: 'If it would startle a sheep on Tegg’s Nose, it belongs here.',
    },
    {
      id: 'sangeet',
      title: 'Sangeet',
      date: 'Friday, 2 October 2026',
      time: '7:00 PM',
      venue: 'Venue name',
      address: 'Street, City',
      description:
        'Performances, dancing, and a night that belongs on screen. Bring your best moves.',
      theme: 'sangeet',
      icon: '♪',
      dressCode: 'Dress to impress',
      dressNote:
        'No hiking boots required for this one — though comfortable dancing shoes are encouraged!',
    },
    {
      id: 'reception',
      title: 'Reception',
      date: 'Sunday, 4 October 2026',
      time: '6:00 PM',
      venue: 'Venue name',
      address: 'Street, City',
      description:
        'An evening of dinner, music, and slow celebration with everyone we love.',
      theme: 'reception',
      icon: '✦',
      dressCode: 'Dress to impress',
      dressNote:
        'No hiking boots required for this one — though comfortable dancing shoes are encouraged!',
    },
  ],
  gallery: [
    { src: '/images/gallery/2025-09-23.jpg', alt: 'Thamanna and Samar' },
    { src: '/images/gallery/2025-09-23(1).jpg', alt: 'Thamanna and Samar' },
    { src: '/images/gallery/2025-09-23(2).jpg', alt: 'Thamanna and Samar' },
    { src: '/images/gallery/2025-09-23(3).jpg', alt: 'Thamanna and Samar' },
    { src: '/images/gallery/2025-09-23(4).jpg', alt: 'Thamanna and Samar' },
    { src: '/images/gallery/2025-09-23(5).jpg', alt: 'Thamanna and Samar' },
    { src: '/images/gallery/2025-09-23(6).jpg', alt: 'Thamanna and Samar' },
    { src: '/images/gallery/2025-09-23(7).jpg', alt: 'Thamanna and Samar' },
    { src: '/images/gallery/2025-09-23(8).jpg', alt: 'Thamanna and Samar' },
    { src: '/images/gallery/2025-09-23(9).jpg', alt: 'Thamanna and Samar' },
    { src: '/images/gallery/2025-09-23(10).jpg', alt: 'Thamanna and Samar' },
    { src: '/images/gallery/2025-09-23(11).jpg', alt: 'Thamanna and Samar' },
    { src: '/images/gallery/2025-09-23(12).jpg', alt: 'Thamanna and Samar' },
    { src: '/images/gallery/2025-09-23(13).jpg', alt: 'Thamanna and Samar' },
    { src: '/images/gallery/2025-09-23(14).jpg', alt: 'Thamanna and Samar' },
    { src: '/images/gallery/2025-09-23(15).jpg', alt: 'Thamanna and Samar' },
    { src: '/images/gallery/2025-09-23(16).jpg', alt: 'Thamanna and Samar' },
    { src: '/images/gallery/2025-09-23(17).jpg', alt: 'Thamanna and Samar' },
    { src: '/images/gallery/2025-09-23(18).jpg', alt: 'Thamanna and Samar' },
    { src: '/images/gallery/2025-09-25.jpg', alt: 'Thamanna and Samar' },
    { src: '/images/gallery/2025-09-25(1).jpg', alt: 'Thamanna and Samar' },
    { src: '/images/gallery/2025-09-25(2).jpg', alt: 'Thamanna and Samar' },
    { src: '/images/gallery/2025-09-25(3).jpg', alt: 'Thamanna and Samar' },
    { src: '/images/gallery/2025-09-25(4).jpg', alt: 'Thamanna and Samar' },
    { src: '/images/gallery/2025-09-25(5).jpg', alt: 'Thamanna and Samar' },
    { src: '/images/gallery/2025-09-25(6).jpg', alt: 'Thamanna and Samar' },
    { src: '/images/gallery/2025-09-25(7).jpg', alt: 'Thamanna and Samar' },
    { src: '/images/gallery/2025-09-25(8).jpg', alt: 'Thamanna and Samar' },
    { src: '/images/gallery/2025-09-25(9).jpg', alt: 'Thamanna and Samar' },
    { src: '/images/gallery/2025-09-25(10).jpg', alt: 'Thamanna and Samar' },
    { src: '/images/gallery/2025-09-25(11).jpg', alt: 'Thamanna and Samar' },
    { src: '/images/gallery/2025-09-25(12).jpg', alt: 'Thamanna and Samar' },
    { src: '/images/gallery/2025-09-25(13).jpg', alt: 'Thamanna and Samar' },
    { src: '/images/gallery/2025-09-25(14).jpg', alt: 'Thamanna and Samar' },
    { src: '/images/gallery/2025-09-25(15).jpg', alt: 'Thamanna and Samar' },
    { src: '/images/gallery/2025-09-25(16).jpg', alt: 'Thamanna and Samar' },
    { src: '/images/gallery/2025-09-25(17).jpg', alt: 'Thamanna and Samar' },
    { src: '/images/gallery/2025-09-25(18).jpg', alt: 'Thamanna and Samar' },
  ],
  feed: {
    stories: [
      {
        id: 'engagement',
        label: 'Engagement',
        status: 'replay',
        image: '/images/gallery/2025-09-23.jpg',
      },
      {
        id: 'nikah',
        label: 'Nikah',
        status: 'replay',
        image: '/images/gallery/2025-09-25.jpg',
      },
      {
        id: 'live',
        label: 'Live',
        status: 'live',
        image: '/images/gallery/2025-09-25(3).jpg',
      },
      { id: 'haldi', label: 'Haldi', status: 'coming', icon: '✿' },
      { id: 'mehendi', label: 'Mehendi', status: 'coming', icon: '❦' },
      { id: 'sangeet', label: 'Sangeet', status: 'coming', icon: '♪' },
      { id: 'reception', label: 'Reception', status: 'coming', icon: '✦' },
    ],
    posts: [
      {
        date: '2026-08-17T10:30:00+05:30',
        author: 'Thamanna & Samar',
        handle: '@tands',
        body: 'Fittings, flower trials, and a very opinionated tasting spoon. We are in the thick of it — more as it happens.',
        image: '/images/gallery/2025-09-25(3).jpg',
        imageAlt: 'Thamanna and Samar',
        likes: 48,
        live: true,
      },
      {
        date: '2026-08-10T16:00:00+05:30',
        author: 'Thamanna & Samar',
        handle: '@tands',
        body: 'Save the dates are out. The first round of invitations has gone — reply whenever you can, we are keeping a list.',
        image: '/images/gallery/2025-09-23(4).jpg',
        imageAlt: 'Thamanna and Samar',
        likes: 112,
      },
      {
        date: '2026-07-22T19:45:00+05:30',
        author: 'Thamanna & Samar',
        handle: '@tands',
        body: 'Three rounds of biryani later, we have finally agreed on the reception menu.',
        likes: 86,
      },
      {
        date: '2026-06-15T11:20:00+05:30',
        author: 'Thamanna & Samar',
        handle: '@tands',
        body: 'All four celebrations now have a home. Details on each are in the events section.',
        image: '/images/gallery/2025-09-23.jpg',
        imageAlt: 'Thamanna and Samar',
        likes: 64,
      },
      {
        date: '2025-05-31T18:00:00+05:30',
        author: 'Thamanna & Samar',
        handle: '@tands',
        body: 'Already married. Still celebrating. A quiet day we will never forget.',
        image: '/images/gallery/2025-09-25.jpg',
        imageAlt: 'Thamanna and Samar on their Nikah day',
        likes: 240,
      },
    ],
  },
  photoUpload: {
    url: '',
    note: 'Took a photo you love? Scan the code and drop it into our shared album — we want to see the night through your eyes.',
  },
  rsvp: {
    /** Optional Formspree URL. Leave empty to keep replies in the browser for now. */
    endpoint: '',
    deadline: '1 September 2026',
    note: 'We would love to know if you will be present for the events.',
  },
  trail: {
    title: 'The Trail So Far',
    lede: 'Tap each pin and walk the path with us — from a first hello in Macclesfield to the day we said I do.',
    stops: [
      {
        id: 'macclesfield',
        title: 'Macclesfield',
        kicker: 'Where it began',
        description:
          '11 September, in the hills above town. A chance meeting, a sudden calm — as if the Peak District had been keeping a seat for us.',
        mapUrl: 'https://maps.google.com/?q=Macclesfield',
      },
      {
        id: 'dorset',
        title: 'Dorset',
        kicker: 'He asked',
        description:
          'On the Dorset coast, Samar asked the first question — a quiet moment by the sea, and a yes that started everything properly.',
        mapUrl: 'https://maps.google.com/?q=Dorset',
      },
      {
        id: 'pepper-house',
        title: 'Pepper House, Kochi',
        kicker: 'She asked',
        description:
          'At Pepper House in Kochi, Thamanna returned the question. Two proposals, two yeses — and a story we still love telling.',
        mapUrl: 'https://maps.google.com/?q=Pepper+House+Kochi',
      },
      {
        id: 'hyatt',
        title: 'Hyatt Regency, Thrissur',
        kicker: 'The day we said I do',
        description:
          'Our Nikah at Hyatt Regency, Thrissur — 31 May 2025. The day we became husband and wife, surrounded by everyone we love.',
        mapUrl: 'https://maps.google.com/?q=Hyatt+Regency+Thrissur',
      },
      {
        id: 'home',
        title: 'Where We Live',
        kicker: 'Plot twist',
        description: 'Haha, tricked you! You are a nosy one.',
      },
    ],
  },
  quiz: {
    title: 'A Little Trivia',
    lede: 'Three questions. No prizes, plenty of opinions. Vote like you were on the ridge with us.',
    questions: [
      {
        id: 'hike',
        prompt: 'Who survived the hike better on Day 1?',
        options: [
          { id: 'thamanna', label: 'Thamanna' },
          { id: 'samar', label: 'Samar' },
          { id: 'tie', label: 'They both needed a sit-down' },
        ],
        coupleNote: 'Samar claims the summit. Thamanna claims the moral victory. The tea room claims them both.',
      },
      {
        id: 'tea',
        prompt: 'How many cups of tea do we drink together in a week?',
        options: [
          { id: 'four', label: 'A polite four' },
          { id: 'eight', label: 'About eight' },
          { id: 'twelve', label: 'Twelve, easily' },
          { id: 'lost', label: 'We lost count' },
        ],
        coupleNote: 'The official tally is “we lost track around cup nine.” The kettle disagrees.',
      },
      {
        id: 'lost',
        prompt: 'Who is more likely to get lost on a trail?',
        options: [
          { id: 'thamanna', label: 'Thamanna' },
          { id: 'samar', label: 'Samar' },
          { id: 'both', label: 'Both, confidently' },
        ],
        coupleNote: 'One packed the map. The other packed confidence. A sheep was asked for directions.',
      },
    ],
  },
  guide: {
    title: 'Our Favourite Local Hikes & Coffee Spots',
    lede: 'If you are travelling in, walk a little of the story. These are the hills and cups that started it.',
    places: [
      {
        title: 'Tegg’s Nose',
        kind: 'hike',
        note: 'Where we became trail mates. Short enough for a morning, big enough for the view. Finish at the tea room — non-negotiable.',
        mapUrl: 'https://maps.google.com/?q=Tegg%27s+Nose+Country+Park',
      },
      {
        title: 'Shutlingsloe',
        kind: 'hike',
        note: 'The Cheshire Matterhorn, if you like a nickname with your climb. Steep, quick, and excellent for pretending you are braver than Day 1.',
        mapUrl: 'https://maps.google.com/?q=Shutlingsloe',
      },
      {
        title: 'The Cloud',
        kind: 'hike',
        note: 'Bosley Cloud — a ridge with a proper payoff. Pack a layer. The wind has opinions.',
        mapUrl: 'https://maps.google.com/?q=The+Cloud+Bosley',
      },
      {
        title: 'Tegg’s Nose Tea Room',
        kind: 'coffee',
        note: 'The first cup. Cake is not optional. If the windows are steamed up, you are in the right place.',
        mapUrl: 'https://maps.google.com/?q=Tegg%27s+Nose+Tea+Room',
      },
      {
        title: 'A brew in Macclesfield',
        kind: 'coffee',
        note: 'Wander the town after the hills. Find a corner table, order whatever is warming, and toast the day we met.',
        mapUrl: 'https://maps.google.com/?q=Macclesfield+coffee',
      },
    ],
  },
}
